# -*- coding: utf-8 -*-
{
    'name': 'Ronix Yemek Teslimat Platformu',
    'version': '1.0',
    'summary': 'Restoran, sipariş, sepet, adres ve teslimat akışlarını yöneten yemek teslimat uygulaması',
    'description': """
Ronix Yemek Teslimat Platformu
==============================

Restoran listeleme, ürün seçimi, sepet, ödeme, favoriler,
adres yönetimi, sipariş takibi ve restoran değerlendirmelerini
tek akışta sunan kapsamlı bir yemek teslimat çözümüdür.
    """,
    'author': 'Cantay Aktura',
    'website': 'https://www.lugatsoft.com',
    'category': 'Website',
    'depends': [
        'base',
        'website',
        'website_sale',
        'sale',
        # 'corders',
    ],
    'data': [
        'security/ronix_food_delivery_security.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'views/food_home_template.xml',
        'views/food_modals_template.xml',
        'views/food_cart_template.xml',
        'views/food_orders_template.xml',
        'views/food_profile_template.xml',
        'views/food_restaurant_template.xml',
        'views/food_favorites_template.xml',
        'views/food_account_template.xml',
        'views/food_addresses_template.xml',
        'views/food_payment_methods_template.xml',
        'views/food_settings_template.xml',
        'views/sale_order_view.xml',
        'views/food_orders_backend_views.xml',
        'views/food_coupons_template.xml',
        'views/food_notifications_template.xml',
        'views/food_all_restaurants_template.xml',
        'views/food_popular_foods_template.xml',
        'views/food_favorite_restaurants_template.xml',
        'views/food_support_template.xml',
        'views/food_restaurant_views.xml',
        'views/food_delivery_address_views.xml',
        'views/food_product_views.xml',
        'views/food_offcanvas_template.xml',
        'views/food_checkout_payment_template.xml',
        'views/food_review_tag_views.xml',
        'views/food_order_cancel_wizard_views.xml',
        'views/res_config_settings_views.xml',
        'data/review_default_tags.xml',
        'data/tip_product_data.xml',
        'data/delivery_fee_data.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.min.css',
            'https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css',
            'ronix_food_delivery/static/src/css/food_home.css',
            'ronix_food_delivery/static/src/js/food_home.js',
            'ronix_food_delivery/static/src/js/address_management.js',
            'ronix_food_delivery/static/src/js/food_favorites.js',
            'ronix_food_delivery/static/src/js/food_offcanvas.js',
            'ronix_food_delivery/static/src/js/food_search.js',
            'ronix_food_delivery/static/src/js/food_cart.js',
            'ronix_food_delivery/static/src/js/food_checkout.js',
            'ronix_food_delivery/static/src/js/food_orders.js',
            'ronix_food_delivery/static/src/js/food_reviews.js',
        ],
        'web.assets_backend': [
            'ronix_food_delivery/static/src/js/backend_new_order_alert.js',
            'ronix_food_delivery/static/src/js/ronix_timer_widget.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
